### ISSUE TITLE
1.9 fails to build with 8.4.3

### ISSUE THREAD

**Issue by steinitznavican** [timbod7/haskell-chart#195]
```
Configuring Chart-diagrams-1.9...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:958:20 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:462:12 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.2.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.2.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.2.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.2.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:8:8 in main:Main
Setup: Encountered missing dependencies:
SVGFonts >=1.4 && <1.7
```

I'm using nix so I did `(nixpkgs.haskell.lib.doJailbreak haskellPackages.Chart-diagrams)` but then I get

```
[2 of 2] Compiling Graphics.Rendering.Chart.Backend.Diagrams ( Graphics/Rendering/Chart/Backend/Diagrams.hs, dist/build/Graphics/Rendering/Chart/Backend/Diagrams.o )

Graphics/Rendering/Chart/Backend/Diagrams.hs:573:14: error:
    • Couldn't match type ‘IO (F.PreparedFont Double)’
                     with ‘(F.FontData n, F.OutlineMap n)’
      Expected type: F.PreparedFont n
        Actual type: IO (F.PreparedFont Double)
    • In the expression: F.lin
      In a case alternative: "serif" -> F.lin
      In the expression:
        case name of
          "serif" -> F.lin
          "monospace" -> F.bit
          _ -> F.lin
    • Relevant bindings include
        fontFromName :: String -> F.PreparedFont n
          (bound at Graphics/Rendering/Chart/Backend/Diagrams.hs:572:1)
    |
573 |   "serif" -> F.lin
    |              ^^^^^

Graphics/Rendering/Chart/Backend/Diagrams.hs:574:18: error:
    • Couldn't match type ‘IO (F.PreparedFont Double)’
                     with ‘(F.FontData n, F.OutlineMap n)’
      Expected type: F.PreparedFont n
        Actual type: IO (F.PreparedFont Double)
    • In the expression: F.bit
      In a case alternative: "monospace" -> F.bit
      In the expression:
        case name of
          "serif" -> F.lin
          "monospace" -> F.bit
          _ -> F.lin
    • Relevant bindings include
        fontFromName :: String -> F.PreparedFont n
          (bound at Graphics/Rendering/Chart/Backend/Diagrams.hs:572:1)
    |
574 |   "monospace" -> F.bit
    |                  ^^^^^

Graphics/Rendering/Chart/Backend/Diagrams.hs:575:8: error:
    • Couldn't match type ‘IO (F.PreparedFont Double)’
                     with ‘(F.FontData n, F.OutlineMap n)’
      Expected type: F.PreparedFont n
        Actual type: IO (F.PreparedFont Double)
    • In the expression: F.lin
      In a case alternative: _ -> F.lin
      In the expression:
        case name of
          "serif" -> F.lin
          "monospace" -> F.bit
          _ -> F.lin
    • Relevant bindings include
        fontFromName :: String -> F.PreparedFont n
          (bound at Graphics/Rendering/Chart/Backend/Diagrams.hs:572:1)
    |
575 |   _ -> F.lin
    |        ^^^^^
builder for '/nix/store/j0y2ynscn4j6r05w8a5dc3h4qylv3199-Chart-diagrams-1.9.drv' failed with exit code 1
cannot build derivation '/nix/store/zxlwi74wy8kchhxwz757fr5lkdpbmf03-ghc-8.4.3-with-packages.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s73ijjfj3356dc9mlgqgpa1xq3aa8hzd-ihaskell-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/s73ijjfj3356dc9mlgqgpa1xq3aa8hzd-ihaskell-with-packages.drv' failed
```

**Comment by timbod7** [comment]
This is your problem:

```
Setup: Encountered missing dependencies:
SVGFonts >=1.4 && <1.7
```
chart-diagrams needs a version of SVGFonts inside that range. I'm not sure what nix jailbreak does, but it  picked up SVGFonts-1.7, which has API breaking changes.

**Comment by steinitznavican** [comment]
`jailbreak` breaks the bounds so you aren't stuck by packages that haven't updated their upper bounds.
