### ISSUE TITLE
Fails to build on GHC 8.6.1

### ISSUE THREAD

**Issue by BardurArantsson** [timbod7/haskell-chart#192]
I'm getting the following error when building on GHC 8.6.1:

```
[35 of 37] Compiling Graphics.Rendering.Chart.State ( Graphics/Rendering/Chart/State.hs, dist/build/Graphics/Rendering/Chart/State.o )

Graphics/Rendering/Chart/State.hs:95:3: error:
    • No instance for (Control.Monad.Fail.MonadFail Identity)
        arising from a do statement
        with the failable pattern ‘(c : cs)’
    • In a stmt of a 'do' block: (c : cs) <- use colors
      In the second argument of ‘($)’, namely
        ‘do (c : cs) <- use colors
            colors .= cs
            return c’
      In the expression:
        liftCState
          $ do (c : cs) <- use colors
               colors .= cs
               return c
   |
95 |   (c:cs) <- use colors
   |   ^^^^^^^^^^^^^^^^^^^^

Graphics/Rendering/Chart/State.hs:102:3: error:
    • No instance for (Control.Monad.Fail.MonadFail Identity)
        arising from a do statement
        with the failable pattern ‘(c : cs)’
    • In a stmt of a 'do' block: (c : cs) <- use shapes
      In the second argument of ‘($)’, namely
        ‘do (c : cs) <- use shapes
            shapes .= cs
            return c’
      In the expression:
        liftCState
          $ do (c : cs) <- use shapes
               shapes .= cs
               return c
    |
102 |   (c:cs) <- use shapes
    |   ^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build Chart-1.9 (which is required by exe:foo from
foo-0.1.0). See the build log above for details.
```

(This is using Chart-1.9.)

I'm using the command

```
cabal new-build --allow-newer=base,lens
```

to build.

**Comment by timbod7** [comment]
Looks like we need to follow the instructions here: 

https://ghc.haskell.org/trac/ghc/wiki/Migration/8.6

**Comment by BardurArantsson** [comment]
Ah, yes, I'd actually tried looking at that to figure out what was going on, but it seems I missed the 

https://ghc.haskell.org/trac/ghc/wiki/Migration/8.6#MonadFailDesugaringbydefault

bit. Should actually be a reasonable simple fix, but I'm not sure about backward-compat to <=8.4.x. I'm guessing there's allowances for down to 8.0.x or 8.2.x, but obviously I haven't tried to do this adaptation.

**Comment by timbod7** [comment]
I don't have ghc 8.6 yet. Can you try this fix:

**Comment by BardurArantsson** [comment]
Unfortunately, I'm having a little trouble setting up a vendored copy of haskell-chart right now, but I'll give it a proper go tomorrow. (Just looking at it, I think it's safe to assume that your proposed code will work, but I'll try to get confirmation tomorrow.)

Thanks for the help so far!

**Comment by BardurArantsson** [comment]
Alright, I've confirmed that those changes are enough. The rest of the code "after" State.hs also compiles cleanly, so that should be enough to get everything working on GHC 8.6 :+1: 

(I'm only using "Chart" and "Chart-diagrams", so no idea about the rest of the packages.)

**Comment by cevantes** [comment]
@BardurArantsson Care to submit a PR?

**Comment by BardurArantsson** [comment]
Not mine, but here's a prettier fix: https://github.com/timbod7/haskell-chart/pull/197

**Comment by BardurArantsson** [comment]
Fixed by #197 which was merged, so closing this one :).
