### ISSUE TITLE
Chart-1.9.5 fails to build with GHC 8.2

### ISSUE THREAD

**Issue by andreasabel** [timbod7/haskell-chart#259]
https://github.com/andreasabel/agda-issues/actions/runs/18942700454/job/54105654492#step:20:84
```
Building library for Chart-1.9.5...
[ 1 of 37] Compiling Graphics.Rendering.Chart.Geometry ( Graphics/Rendering/Chart/Geometry.hs, dist/build/Graphics/Rendering/Chart/Geometry.o )

Graphics/Rendering/Chart/Geometry.hs:198:10: error:
    Not in scope: type constructor or class ‘Semigroup’
```
