### ISSUE TITLE
Is it possible to fix Chart-diagrams to work with SVGFonts 1.8

### ISSUE THREAD

**Issue by expipiplus1** [timbod7/haskell-chart#232]
There are a few breaking changes which need to be accommodated. I had a glance at fixing these but some were non-obvious.

```
Graphics/Rendering/Chart/Backend/Diagrams.hs:398:59: error:
    Not in scope: ‘F.textSVG'’
    Perhaps you meant ‘F.textSVG’ (imported from Graphics.SVGFonts)
    Neither ‘Graphics.SVGFonts’,
            ‘Graphics.SVGFonts.CharReference’ nor ‘Graphics.SVGFonts.ReadFont’ exports ‘textSVG'’.
    |
398 |                 { textSizeWidth = realToFrac $ D2.width $ F.textSVG' (fontStyleToTextOpts env) text
    |                                                           ^^^^^^^^^^

Graphics/Rendering/Chart/Backend/Diagrams.hs:418:12: error:
    Not in scope: ‘F.textSVG_’
    Perhaps you meant ‘F.textSVG’ (imported from Graphics.SVGFonts)
    Neither ‘Graphics.SVGFonts’,
            ‘Graphics.SVGFonts.CharReference’ nor ‘Graphics.SVGFonts.ReadFont’ exports ‘textSVG_’.
    |
418 |          $ F.textSVG_ (fontStyleToTextOpts env) text
    |            ^^^^^^^^^^

Graphics/Rendering/Chart/Backend/Diagrams.hs:578:9: error:
    Not in scope: ‘F.mode’
    Neither ‘Graphics.SVGFonts’,
            ‘Graphics.SVGFonts.CharReference’ nor ‘Graphics.SVGFonts.ReadFont’ exports ‘mode’.
    |
578 |       , F.mode = F.INSIDE_H
    |         ^^^^^^

Graphics/Rendering/Chart/Backend/Diagrams.hs:578:18: error:
    Not in scope: data constructor ‘F.INSIDE_H’
    Neither ‘Graphics.SVGFonts’,
            ‘Graphics.SVGFonts.CharReference’ nor ‘Graphics.SVGFonts.ReadFont’ exports ‘INSIDE_H’.
    |
578 |       , F.mode = F.INSIDE_H
    |                  ^^^^^^^^^^

Graphics/Rendering/Chart/Backend/Diagrams.hs:581:9: error:
    Not in scope: ‘F.textWidth’
    Neither ‘Graphics.SVGFonts’,
            ‘Graphics.SVGFonts.CharReference’ nor ‘Graphics.SVGFonts.ReadFont’ exports ‘textWidth’.
    |
581 |       , F.textWidth = 1
    |         ^^^^^^^^^^^

Graphics/Rendering/Chart/Backend/Diagrams.hs:582:9: error:
    Not in scope: ‘F.textHeight’
    Neither ‘Graphics.SVGFonts’,
            ‘Graphics.SVGFonts.CharReference’ nor ‘Graphics.SVGFonts.ReadFont’ exports ‘textHeight’.
    |
582 |       , F.textHeight = scaledH -- _font_size fs
    |         ^^^^^^^^^^^^
```

**Comment by expipiplus1** [comment]
Yeah, it's regrettable that SVGFonts has dropped off Stackage, although I guess if it's ever put back in it'll be the latest version.

**Comment by byorgey** [comment]
Just wanted to mention here that I put together a migration guide for `SVGFonts-1.8`: https://github.com/diagrams/SVGFonts#porting-to-version-18 .  If you like, I'd be happy to help put together a PR to update `Chart`.

**Comment by timbod7** [comment]
Thanks @byorgey. I'll take a look at the migration advice.

**Comment by bravit** [comment]
Thanks, @byorgey, I'll look into this today.

**Comment by bravit** [comment]
Fixed with https://github.com/timbod7/haskell-chart/commit/91d82bf719d93e3092fc6e2087a62f24b14b0b76
